import Head from "next/head";
import Hero from "../../components/hero/Hero";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { fetchrandomVideos } from "../../api/videos/videos";
import { AppDispatch } from "../../redux/store";

export default function Home() {
  const dispatch = useDispatch<AppDispatch>();

  useEffect(() => {
    dispatch(fetchrandomVideos());
  }, []);
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Hero />
      </div>
    </>
  );
}
